---
apiVersion: apiextensions.k8s.io/v1alpha1
kind: CustomResourceDefinition
metadata:
  annotations:
  name: recipes.metacontroller.io.app
spec:
  group: metacontroller.io.app
  names:
    kind: Recipe
    listKind: RecipeList
    plural: recipes
    shortNames:
    - rp
    singular: recipe
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true