---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
  name: recipes.dope.metacontroller.io
spec:
  group: dope.metacontroller.io
  names:
    kind: Recipe
    listKind: RecipeList
    plural: recipes
    shortNames:
    - rcp
    singular: recipe
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true