---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
  name: jobs.metacontroller.app
spec:
  group: metacontroller.app
  names:
    kind: Job
    listKind: JobList
    plural: jobs
    shortNames:
    - jb
    singular: job
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true