---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
  name: recipes.dope.mayadata.io
spec:
  group: dope.mayadata.io
  names:
    kind: Recipe
    listKind: RecipeList
    plural: recipes
    shortNames:
    - rcp
    singular: recipe
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
  name: https.dope.mayadata.io
spec:
  group: dope.mayadata.io
  names:
    kind: HTTP
    listKind: HTTPList
    plural: https
    shortNames:
    - http
    singular: http
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true