apiVersion: v1
kind: ServiceAccount
metadata:
  name: dope
  namespace: dope
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dope
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dope
subjects:
- kind: ServiceAccount
  name: dope
  namespace: dope
roleRef:
  kind: ClusterRole
  name: dope
  apiGroup: rbac.authorization.k8s.io