apiVersion: dope/v1
kind: GenericController
metadata:
  name: sync-recipe
  namespace: dope
spec:
  watch:
    apiVersion: dope.mayadata.io/v1
    resource: recipes
  hooks:
    sync:
      inline:
        funcName: sync/recipe
---
apiVersion: dope/v1
kind: GenericController
metadata:
  name: finalize-recipe
  namespace: dope
spec:
  watch: 
    apiVersion: dope.mayadata.io/v1
    resource: recipes
  attachments:
  - apiVersion: v1
    resource: configmaps
    advancedSelector:
      selectorTerms:
      # select ConfigMap if its labels has following
      - matchLabels:
          recipe.dope.mayadata.io/lock: "true"
        matchReferenceExpressions:
        - key: metadata.labels.recipe\.dope\.mayadata\.io/name
          operator: EqualsWatchName # match this lbl value against watch Name
  hooks:
    finalize:
      inline:
        funcName: finalize/recipe
---
apiVersion: dope/v1
kind: GenericController
metadata:
  name: sync-http
  namespace: dope
spec:
  watch: 
    # kind: HTTP custom resource is watched
    apiVersion: dope.mayadata.io/v1
    resource: https
  hooks:
    sync:
      inline:
        funcName: sync/http
---
apiVersion: dope/v1
kind: GenericController
metadata:
  name: sync-command
  namespace: dope
spec:
  watch:
    apiVersion: dope.mayadata.io/v1
    resource: commands
  hooks:
    sync:
      inline:
        funcName: sync/command
---
apiVersion: dope/v1
kind: GenericController
metadata:
  name: finalize-command
  namespace: dope
spec:
  watch:
    apiVersion: dope.mayadata.io/v1
    resource: commands
  attachments:
  # Delete pod
  - apiVersion: v1
    resource: pods
    advancedSelector:
      selectorTerms:
      # select Pod if it has following label
      - matchLabels:
        matchReferenceExpressions:
        - key: metadata.labels.job-name
          operator: EqualsWatchName # match this lbl value against watch Name
  # Delete job
  - apiVersion: batch/v1
    resource: jobs
    advancedSelector:
      selectorTerms:
      # select job if its labels has following
      - matchLabels:
          command.dope.mayadata.io/controller: "true"
        matchReferenceExpressions:
        - key: metadata.labels.command\.dope\.mayadata\.io/name
          operator: EqualsWatchName # match this lbl value against watch Name
  - apiVersion: v1
    resource: configmaps
    advancedSelector:
      selectorTerms:
      # select ConfigMap if its labels has following
      - matchLabels:
          command.dope.mayadata.io/lock: "true"
        matchReferenceExpressions:
        - key: metadata.labels.command\.dope\.mayadata\.io/name
          operator: EqualsWatchName # match this lbl value against watch Name
  hooks:
    finalize:
      inline:
        funcName: finalize/command
---
