apiVersion: metac.openebs.io/v1alpha1
kind: GenericController
metadata:
  name: sync-recipe
  namespace: dope
spec:
  watch: # kind: Recipe custom resource is watched
    apiVersion: dope.metacontroller.io/v1
    resource: recipes
  hooks:
    sync:
      inline:
        funcName: sync/recipe
---