name: Docker Image CI

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
    paths-ignore:
    - 'docs/**'
    - 'deploy/**'
    - '*.md'
  pull_request:
    branches:
    - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Initial image tag identification
      run: |
        echo ${{ github.ref }} | sed -e 's/^refs\/heads\///g' -e 's/^refs\/tags\///g' -e 's/^refs\/pull\///g' -e 's/\/merge$//g' | sed -e 's/master/latest/g' > IMAGE_TAG
        echo "Tagging image with '$(cat IMAGE_TAG)'"
      
    - name: Build the Docker image
      run: |
        IMAGE_TAG=$(cat IMAGE_TAG)
        docker build . --file Dockerfile --tag mayadataio/d-operator:${IMAGE_TAG}
        IMAGEID=$(docker images -q mayadataio/d-operator:${IMAGE_TAG} )
      
    - name: Push the Docker image for non-release commits 
      if: github.event_name != 'pull_request'
      run: |
        docker tag ${IMAGEID} mayadataio/d-operator:ci
        docker login -u "${DNAME}" -p "${DPASS}"
        docker push mayadataio/d-operator:ci
         
